name: Build
on: workflow_dispatch

env:
  APP_VERSION: '2.7.8'
  SCHEME_NAME: 'EhPanda'
  BUILDS_PATH: '/tmp/action-builds'
  PAYLOAD_PATH: '/tmp/action-builds/Payload'
  THIN_PAYLOAD_SCRIPT_PATH: './actions-tool/thin-payload.sh'
  ARCHIVE_PATH: '/tmp/action-builds/EhPanda.xcarchive'
  IPA_OUTPUT_PATH: '/tmp/action-builds/EhPanda.ipa'

jobs:
  Build:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Bump version
        id: bump-version
        uses: yanamura/ios-bump-version@v1
        with:
          version: ${{ env.APP_VERSION }}
      - name: Xcode archive
        run: xcodebuild archive
          -skipMacroValidation
          -scheme ${{ env.SCHEME_NAME }}
          -destination 'generic/platform=iOS'
          -archivePath ${{ env.ARCHIVE_PATH }}
          CODE_SIGN_IDENTITY=
          CODE_SIGN_ENTITLEMENTS=
          CODE_SIGNING_ALLOWED=NO
          CODE_SIGNING_REQUIRED=NO
          GCC_OPTIMIZATION_LEVEL=s
          SWIFT_OPTIMIZATION_LEVEL=-O
      - name: Export .ipa file
        run: |
          mkdir -p ${{ env.PAYLOAD_PATH }}
          mv ${{ env.ARCHIVE_PATH }}/Products/Applications/${{ env.SCHEME_NAME }}.app ${{ env.PAYLOAD_PATH }}/${{ env.SCHEME_NAME }}.app
          sh ${{ env.THIN_PAYLOAD_SCRIPT_PATH }} ${{ env.PAYLOAD_PATH }}/${{ env.SCHEME_NAME }}.app
          pushd ${{ env.BUILDS_PATH }}
          zip -r ${{ env.IPA_OUTPUT_PATH }} ./Payload
          popd
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: EhPanda.ipa
          path: ${{ env.IPA_OUTPUT_PATH }}
